import { useEffect, useMemo, useState } from 'react'
import { api } from '../../../shared/api/client'
import { useAuth } from '../../auth/context/AuthContext'
import { Alert, money, PageHeader } from '../../../shared/ui/Ui'
import EntryTable from '../components/EntryTable'

export default function WorkerDashboard() {
  const { user } = useAuth(); const today = new Date().toISOString().slice(0, 10)
  const [products, setProducts] = useState([]); const [entries, setEntries] = useState([]); const [form, setForm] = useState({ productId: '', workDate: today, quantity: '', notes: '' }); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const load = () => Promise.all([api('/products'), api(`/work-entries?from=${today}&to=${today}`)]).then(([p, e]) => { setProducts(p.filter(x => x.isActive)); setEntries(e) }).catch(x => setMessage(x.message)); useEffect(() => { load() }, [])
  const selected = products.find(x => x.id === Number(form.productId)); const expected = useMemo(() => Number(form.quantity || 0) * Number(selected?.ratePerUnit || 0), [form.quantity, selected])
  async function submit(e) { e.preventDefault(); setMessage(''); setBusy(true); try { await api('/work-entries', { method: 'POST', body: JSON.stringify({ ...form, productId: Number(form.productId), quantity: Number(form.quantity) }) }); setMessage('تم تسجيل إنتاجك بنجاح'); setForm({ ...form, productId: '', quantity: '', notes: '' }); await load() } catch (x) { setMessage(x.message) } finally { setBusy(false) } }
  return <section className="page"><PageHeader title={`أهلًا ${user.fullName}`} subtitle="سجّل ما أنجزته اليوم، والنظام سيحسب مستحقك تلقائيًا" /><Alert message={message} type={message.includes('بنجاح') ? 'success' : 'error'} /><div className="worker-grid"><form className="card production-form" onSubmit={submit}><div className="section-heading"><span>✓</span><div><h2>تسجيل إنتاج جديد</h2><p>أدخل نوع العمل والكمية المنجزة</p></div></div><label>نوع العمل<select value={form.productId} onChange={e => setForm({ ...form, productId: e.target.value })} required><option value="">اختر نوع العمل</option>{products.map(x => <option value={x.id} key={x.id}>{x.name} — {money(x.ratePerUnit)} / {x.unitName}</option>)}</select></label><div className="form-row"><label>الكمية<input type="number" min="0.01" step="0.01" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} required /></label><label>تاريخ العمل<input type="date" max={today} value={form.workDate} onChange={e => setForm({ ...form, workDate: e.target.value })} required /></label></div><label>ملاحظات (اختياري)<textarea maxLength="500" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} placeholder="أي تفاصيل إضافية..." /></label><div className="estimate"><span>المستحق المتوقع</span><strong>{money(expected)}</strong></div><button className="primary wide" disabled={busy || !products.length}>{busy ? 'جاري التسجيل...' : products.length ? 'تسجيل الإنتاج' : 'لا توجد أنواع عمل متاحة'}</button></form><div className="card today-card"><div className="card-title"><div><h2>إنتاج اليوم</h2><p>{entries.length} عمليات مسجلة</p></div></div><EntryTable entries={entries} /></div></div></section>
}
