import { useEffect, useState } from 'react'
import { api } from '../../../shared/api/client'
import { Alert, Loading, money, PageHeader } from '../../../shared/ui/Ui'

export default function ProductsPage() {
  const [items, setItems] = useState(null); const [form, setForm] = useState({ name: '', unitName: 'صينية', ratePerUnit: '', isActive: true }); const [error, setError] = useState('')
  const load = () => api('/products').then(setItems).catch(x => { setError(x.message); setItems([]) }); useEffect(() => { load() }, [])
  async function submit(e) { e.preventDefault(); setError(''); try { await api('/products', { method: 'POST', body: JSON.stringify({ ...form, ratePerUnit: Number(form.ratePerUnit) }) }); setForm({ name: '', unitName: 'صينية', ratePerUnit: '', isActive: true }); load() } catch (x) { setError(x.message) } }
  async function toggle(item) { setError(''); try { await api(`/products/${item.id}`, { method: 'PUT', body: JSON.stringify({ name: item.name, unitName: item.unitName, ratePerUnit: item.ratePerUnit, isActive: !item.isActive }) }); load() } catch (x) { setError(x.message) } }
  if (!items) return <Loading />
  return <section className="page"><PageHeader title="أنواع الشغل والأسعار" subtitle="حدّد ما ينتجه العمال وسعر كل وحدة ليُحسب الأجر تلقائيًا" /><Alert message={error} /><div className="split-layout"><form className="card form-card" onSubmit={submit}><div className="section-heading"><span>＋</span><div><h2>إضافة نوع عمل</h2><p>سيظهر مباشرة للعامل عند التسجيل</p></div></div><label>اسم الصنف أو العمل<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="مثال: بقلاوة" required /></label><div className="form-row"><label>وحدة القياس<input value={form.unitName} onChange={e => setForm({ ...form, unitName: e.target.value })} required /></label><label>أجرة الوحدة<input type="number" min="0.01" step="0.01" value={form.ratePerUnit} onChange={e => setForm({ ...form, ratePerUnit: e.target.value })} required /></label></div><button className="primary wide">حفظ نوع العمل</button></form><div className="card"><div className="card-title"><div><h2>الأنواع الحالية</h2><p>{items.length} أنواع مسجلة</p></div></div><div className="product-list">{items.map(x => <div className="product-row" key={x.id}><span className="product-icon">◆</span><div><strong>{x.name}</strong><small>لكل {x.unitName}</small></div><b>{money(x.ratePerUnit)}</b><span className={`badge ${x.isActive ? 'success' : 'muted'}`}>{x.isActive ? 'متاح' : 'موقوف'}</span><button className="row-action" onClick={() => toggle(x)}>{x.isActive ? 'إيقاف' : 'تفعيل'}</button></div>)}</div>{!items.length && <div className="state empty">لا توجد أنواع عمل بعد</div>}</div></div></section>
}
